M48
; DRILL file {KiCad 7.0.2-0} date 2023 August 13, Sunday 19:48:26
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-13T19:48:26+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0866
%
G90
G05
T1
X5.9264Y-5.9892
X6.1539Y-5.9892
T2
X6.7274Y-4.8437
X6.7274Y-4.9618
T3
X5.622Y-2.4291
X5.8583Y-2.4291
T4
X6.3906Y-2.824
T5
X5.2854Y-2.4724
X5.2854Y-6.1004
X6.7949Y-2.4724
X6.7949Y-6.1004
T0
M30
