M48
; DRILL file {KiCad 7.0.2-0} date 2023 August 14, Monday 19:33:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-14T19:33:44+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X6.1748Y-1.7087
X6.1748Y-5.3366
X7.6846Y-1.7087
X7.6846Y-5.3366
T0
M30
